// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf6BH-T1bKOMg0w4Ivc_tqI1r2sC4cJXc',
    appId: '1:295026797859:web:744045cd900e1038c87096',
    messagingSenderId: '295026797859',
    projectId: 'fcm-demo-4e008',
    authDomain: 'fcm-demo-4e008.firebaseapp.com',
    storageBucket: 'fcm-demo-4e008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcftAsOF1IaJMJXjF1WKCrXE82jaZprso',
    appId: '1:295026797859:android:eb8b39902c6cb740c87096',
    messagingSenderId: '295026797859',
    projectId: 'fcm-demo-4e008',
    storageBucket: 'fcm-demo-4e008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3GRgi58RRH2FxwexrYqI_UfzuCPKJ_E',
    appId: '1:295026797859:ios:1b3684f31d4be279c87096',
    messagingSenderId: '295026797859',
    projectId: 'fcm-demo-4e008',
    storageBucket: 'fcm-demo-4e008.appspot.com',
    iosBundleId: 'com.android.fcm.noti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3GRgi58RRH2FxwexrYqI_UfzuCPKJ_E',
    appId: '1:295026797859:ios:1b3684f31d4be279c87096',
    messagingSenderId: '295026797859',
    projectId: 'fcm-demo-4e008',
    storageBucket: 'fcm-demo-4e008.appspot.com',
    iosBundleId: 'com.android.fcm.noti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf6BH-T1bKOMg0w4Ivc_tqI1r2sC4cJXc',
    appId: '1:295026797859:web:017a13aa249481b8c87096',
    messagingSenderId: '295026797859',
    projectId: 'fcm-demo-4e008',
    authDomain: 'fcm-demo-4e008.firebaseapp.com',
    storageBucket: 'fcm-demo-4e008.appspot.com',
  );
}
